CREATE TABLE IF NOT EXISTS msku_master (
    msku_code              TEXT PRIMARY KEY,
    product_classification TEXT,
    style                  TEXT,
    fit                    TEXT,
    brand                  TEXT,
    season                 TEXT,
    price_range            TEXT,
    size                   TEXT,
    mrp                    TEXT,
    moq                    REAL NOT NULL DEFAULT 0,
    lead_time              REAL NOT NULL DEFAULT 0,
    dlt                    REAL NOT NULL DEFAULT 0,
    ltf                    REAL NOT NULL DEFAULT 0,
    vf                     REAL NOT NULL DEFAULT 0,
    doc                    REAL NOT NULL DEFAULT 1,
    active                 INTEGER NOT NULL DEFAULT 1,
    updated_at             TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (moq >= 0),
    CHECK (lead_time >= 0),
    CHECK (dlt >= 0),
    CHECK (ltf >= 0 AND ltf <= 1),
    CHECK (vf  >= 0 AND vf  <= 1),
    CHECK (doc > 0)
);
